const struct {
    uint8_t opcode;
    const char *mnemonic;
    const char *description;
} instructions[] = {
    {0x00, "BRK", "Force an interrupt"},
    {0x01, "ORA (Indirect,X)", "Logical OR with accumulator (Indexed Indirect addressing)"},
    {0x02, "---", "Not available in MOS 6507"},
    {0x03, "---", "Not available in MOS 6507"},
    {0x04, "---", "Not available in MOS 6507"},
    {0x05, "ORA (Zero Page)", "Logical OR with accumulator (Zero Page addressing)"},
    {0x06, "ASL (Zero Page)", "Arithmetic shift left (Zero Page addressing)"},
    {0x07, "---", "Not available in MOS 6507"},
    {0x08, "PHP", "Push processor status onto stack"},
    {0x09, "ORA (Immediate)", "Logical OR with accumulator (Immediate addressing)"},
    {0x0A, "ASL (Accumulator)", "Arithmetic shift left (Accumulator)"},
    {0x0C, "---", "Not available in MOS 6507"},
    {0x0D, "ORA (Absolute)", "Logical OR with accumulator (Absolute addressing)"},
    {0x0E, "ASL (Absolute)", "Arithmetic shift left (Absolute addressing)"},
    {0x0F, "---", "Not available in MOS 6507"},
    {0x10, "BPL", "Branch on result plus (negative clear)"},
    {0x11, "ORA (Indirect),Y", "Logical OR with accumulator (Indirect Indexed addressing)"},
    {0x12, "---", "Not available in MOS 6507"},
    {0x13, "---", "Not available in MOS 6507"},
    {0x14, "---", "Not available in MOS 6507"},
    {0x15, "ORA (Zero Page,X)", "Logical OR with accumulator (Zero Page,X addressing)"},
    {0x16, "ASL (Zero Page,X)", "Arithmetic shift left (Zero Page,X addressing)"},
    {0x17, "---", "Not available in MOS 6507"},
    {0x18, "CLC", "Clear carry flag"},
    {0x19, "ORA (Absolute,Y)", "Logical OR with accumulator (Absolute,Y addressing)"},
    {0x1A, "---", "Not available in MOS 6507"},
    {0x1B, "---", "Not available in MOS 6507"},
    {0x1C, "---", "Not available in MOS 6507"},
    {0x1D, "ORA (Absolute,X)", "Logical OR with accumulator (Absolute,X addressing)"},
    {0x1E, "ASL (Absolute,X)", "Arithmetic shift left (Absolute,X addressing)"},
    {0x20, "JSR", "Jump to subroutine"},
    {0x21, "AND (Indirect,X)", "Logical AND with accumulator (Indexed Indirect addressing)"},
    {0x24, "BIT (Zero Page)", "Test bits in memory with accumulator"},
    {0x25, "AND (Zero Page)", "Logical AND with accumulator (Zero Page addressing)"},
    {0x28, "PLP", "Pull processor status from stack"},
    {0x29, "AND (Immediate)", "Logical AND with accumulator (Immediate addressing)"},
    {0x2A, "ROL (Accumulator)", "Rotate left (Accumulator)"},
    {0x2C, "BIT (Absolute)", "Test bits in memory with accumulator (Absolute addressing)"},
    {0x2D, "AND (Absolute)", "Logical AND with accumulator (Absolute addressing)"},
    {0x30, "BMI", "Branch on result minus (negative set)"},
    {0x31, "AND (Indirect),Y", "Logical AND with accumulator (Indirect Indexed addressing)"},
    {0x35, "AND (Zero Page,X)", "Logical AND with accumulator (Zero Page,X addressing)"},
    {0x38, "SEC", "Set carry flag"},
    {0x39, "AND (Absolute,Y)", "Logical AND with accumulator (Absolute,Y addressing)"},
    {0x3D, "AND (Absolute,X)", "Logical AND with accumulator (Absolute,X addressing)"},
    {0x40, "RTI", "Return from interrupt"},
    {0x41, "EOR (Indirect,X)", "Exclusive OR with accumulator (Indexed Indirect addressing)"},
    {0x45, "EOR (Zero Page)", "Exclusive OR with accumulator (Zero Page addressing)"},
    {0x48, "PHA", "Push accumulator onto stack"},
    {0x49, "EOR (Immediate)", "Exclusive OR with accumulator (Immediate addressing)"},
    {0x4A, "LSR (Accumulator)", "Logical shift right (Accumulator)"},
    {0x4D, "EOR (Absolute)", "Exclusive OR with accumulator (Absolute addressing)"},
    {0x50, "BVC", "Branch on overflow clear"},
    {0x51, "EOR (Indirect),Y", "Exclusive OR with accumulator (Indirect Indexed addressing)"},
    {0x55, "EOR (Zero Page,X)", "Exclusive OR with accumulator (Zero Page,X addressing)"},
    {0x58, "CLI", "Clear interrupt disable flag"},
    {0x59, "EOR (Absolute,Y)", "Exclusive OR with accumulator (Absolute,Y addressing)"},
    {0x5D, "EOR (Absolute,X)", "Exclusive OR with accumulator (Absolute,X addressing)"},
    {0x5E, "LSR (Absolute,X)", "Logical shift right (Absolute,X addressing)"},
    {0x60, "RTS", "Return from subroutine"},
    {0x61, "ADC (Indirect,X)", "Add with carry (Indexed Indirect addressing)"},
    {0x65, "ADC (Zero Page)", "Add with carry (Zero Page addressing)"},
    {0x66, "ROR (Zero Page)", "Rotate right (Zero Page addressing)"},
    {0x68, "PLA", "Pull accumulator from stack"},
    {0x69, "ADC (Immediate)", "Add with carry (Immediate addressing)"},
    {0x6A, "ROR (Accumulator)", "Rotate right (Accumulator)"},
    {0x6D, "ADC (Absolute)", "Add with carry (Absolute addressing)"},
    {0x6E, "ROR (Absolute)", "Rotate right (Absolute addressing)"},
    {0x70, "BVS", "Branch on overflow set"},
    {0x71, "ADC (Indirect),Y", "Add with carry (Indirect Indexed addressing)"},
    {0x75, "ADC (Zero Page,X)", "Add with carry (Zero Page,X addressing)"},
    {0x76, "ROR (Zero Page,X)", "Rotate right (Zero Page,X addressing)"},
    {0x78, "SEI", "Set interrupt disable flag"},
    {0x79, "ADC (Absolute,Y)", "Add with carry (Absolute,Y addressing)"},
    {0x7D, "ADC (Absolute,X)", "Add with carry (Absolute,X addressing)"},
    {0x7E, "ROR (Absolute,X)", "Rotate right (Absolute,X addressing)"},
    {0x80, "---", "Not available in MOS 6507"},
    {0x81, "STA (Indirect,X)", "Store accumulator in memory (Indexed Indirect addressing)"},
    {0x84, "STY (Zero Page)", "Store index Y in memory (Zero Page addressing)"},
    {0x85, "STA (Zero Page)", "Store accumulator in memory (Zero Page addressing)"},
    {0x86, "STX (Zero Page)", "Store index X in memory (Zero Page addressing)"},
    {0x88, "DEY", "Decrement index Y by one"},
    {0x8A, "TXA", "Transfer index X to accumulator"},
    {0x8C, "STY (Absolute)", "Store index Y in memory (Absolute addressing)"},
    {0x8D, "STA (Absolute)", "Store accumulator in memory (Absolute addressing)"},
    {0x8E, "STX (Absolute)", "Store index X in memory (Absolute addressing)"},
    {0x90, "BCC", "Branch on carry clear"},
    {0x91, "STA (Indirect),Y", "Store accumulator in memory (Indirect Indexed addressing)"},
    {0x94, "STY (Zero Page,X)", "Store index Y in memory (Zero Page,X addressing)"},
    {0x95, "STA (Zero Page,X)", "Store accumulator in memory (Zero Page,X addressing)"},
    {0x96, "STX (Zero Page,Y)", "Store index X in memory (Zero Page,Y addressing)"},
    {0x98, "TYA", "Transfer index Y to accumulator"},
    {0x99, "STA (Absolute,Y)", "Store accumulator in memory (Absolute,Y addressing)"},
    {0x9A, "TXS", "Transfer index X to stack pointer"},
    {0x9D, "STA (Absolute,X)", "Store accumulator in memory (Absolute,X addressing)"},
    {0x9F, "---", "Not available in MOS 6507"}, 
    {0xA0, "LDY (Immediate)", "Load index Y with memory (Immediate addressing)"},
    {0xA1, "LDA (Indirect,X)", "Load accumulator with memory (Indexed Indirect addressing)"},
    {0xA2, "LDX (Immediate)", "Load index X with memory (Immediate addressing)"},
    {0xA4, "LDY (Zero Page)", "Load index Y with memory (Zero Page addressing)"},
    {0xA5, "LDA (Zero Page)", "Load accumulator with memory (Zero Page addressing)"},
    {0xA6, "LDX (Zero Page)", "Load index X with memory (Zero Page addressing)"},
    {0xA8, "TAY", "Transfer accumulator to index Y"},
    {0xA9, "LDA (Immediate)", "Load accumulator with memory (Immediate addressing)"},
    {0xAA, "TAX", "Transfer accumulator to index X"},
    {0xAC, "LDY (Absolute)", "Load index Y with memory (Absolute addressing)"},
    {0xAD, "LDA (Absolute)", "Load accumulator with memory (Absolute addressing)"},
    {0xAE, "LDX (Absolute)", "Load index X with memory (Absolute addressing)"},
    {0xB0, "BCS", "Branch on carry set"},
    {0xB1, "LDA (Indirect),Y", "Load accumulator with memory (Indirect Indexed addressing)"},
    {0xB4, "LDY (Zero Page,X)", "Load index Y with memory (Zero Page,X addressing)"},
    {0xB5, "LDA (Zero Page,X)", "Load accumulator with memory (Zero Page,X addressing)"},
    {0xB6, "LDX (Zero Page,Y)", "Load index X with memory (Zero Page,Y addressing)"},
    {0xB8, "CLV", "Clear overflow flag"},
    {0xB9, "LDA (Absolute,Y)", "Load accumulator with memory (Absolute,Y addressing)"},
    {0xBA, "TSX", "Transfer stack pointer to index X"},
    {0xBC, "LDY (Absolute,X)", "Load index Y with memory (Absolute,X addressing)"},
    {0xBD, "LDA (Absolute,X)", "Load accumulator with memory (Absolute,X addressing)"},
    {0xBE, "LDX (Absolute,Y)", "Load index X with memory (Absolute,Y addressing)"},
    {0xC0, "CPY (Immediate)", "Compare memory and index Y (Immediate addressing)"},
    {0xC1, "CMP (Indirect,X)", "Compare memory and accumulator (Indexed Indirect addressing)"},
    {0xC4, "CPY (Zero Page)", "Compare memory and index Y (Zero Page addressing)"},
    {0xC5, "CMP (Zero Page)", "Compare memory and accumulator (Zero Page addressing)"},
    {0xC6, "DEC (Zero Page)", "Decrement memory by one (Zero Page addressing)"},
    {0xC8, "INY", "Increment index Y by one"},
    {0xC9, "CMP (Immediate)", "Compare memory and accumulator (Immediate addressing)"},
    {0xCA, "DEX", "Decrement index X by one"},
    {0xCC, "CPY (Absolute)", "Compare memory and index Y (Absolute addressing)"},
    {0xCD, "CMP (Absolute)", "Compare memory and accumulator (Absolute addressing)"},
    {0xCE, "DEC (Absolute)", "Decrement memory by one (Absolute addressing)"},
    {0xD0, "BNE", "Branch on result not equal (zero clear)"},
    {0xD1, "CMP (Indirect),Y", "Compare memory and accumulator (Indirect Indexed addressing)"},
    {0xD5, "CMP (Zero Page,X)", "Compare memory and accumulator (Zero Page,X addressing)"},
    {0xD6, "DEC (Zero Page,X)", "Decrement memory by one (Zero Page,X addressing)"},
    {0xD8, "CLD", "Clear decimal mode flag"},
    {0xD9, "CMP (Absolute,Y)", "Compare memory and accumulator (Absolute,Y addressing)"},
    {0xDD, "CMP (Absolute,X)", "Compare memory and accumulator (Absolute,X addressing)"},
    {0xDE, "DEC (Absolute,X)", "Decrement memory by one (Absolute,X addressing)"},
    {0xE0, "CPX (Immediate)", "Compare memory and index X (Immediate addressing)"},
    {0xE1, "SBC (Indirect,X)", "Subtract with carry (Indexed Indirect addressing)"},
    {0xE4, "CPX (Zero Page)", "Compare memory and index X (Zero Page addressing)"},
    {0xE5, "SBC (Zero Page)", "Subtract with carry (Zero Page addressing)"},
    {0xE6, "INC (Zero Page)", "Increment memory by one (Zero Page addressing)"},
    {0xE8, "INX", "Increment index X by one"},
    {0xE9, "SBC (Immediate)", "Subtract with carry (Immediate addressing)"},
    {0xEA, "NOP", "No operation"},
    {0xEC, "CPX (Absolute)", "Compare memory and index X (Absolute addressing)"},
    {0xED, "SBC (Absolute)", "Subtract with carry (Absolute addressing)"},
    {0xEE, "INC (Absolute)", "Increment memory by one (Absolute addressing)"},
    {0xF0, "BEQ", "Branch on result equal (zero set)"},
    {0xF1, "SBC (Indirect),Y", "Subtract with carry (Indirect Indexed addressing)"},
    {0xF5, "SBC (Zero Page,X)", "Subtract with carry (Zero Page,X addressing)"},
    {0xF6, "INC (Zero Page,X)", "Increment memory by one (Zero Page,X addressing)"},
    {0xF8, "SED", "Set decimal mode flag"},
    {0xF9, "SBC (Absolute,Y)", "Subtract with carry (Absolute,Y addressing)"},
    {0xFD, "SBC (Absolute,X)", "Subtract with carry (Absolute,X addressing)"},
    {0xFE, "INC (Absolute,X)", "Increment memory by one (Absolute,X addressing)"},
    {0xFF, "---", "Not available in MOS 6507"}
    
};
